# Build Stage
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o core ./cmd/core/main.go

# Run Stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/core .
CMD ["./core"]